backend/README.md
backend/pom.xml
backend/src/main/java/com/backend/backend/ResourceNotFoundException.java
backend/src/main/java/com/backend/backend/chatroom/Chatroom.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomController.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomDto.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomMapper.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomRepository.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomService.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomServiceImpl.java
backend/src/main/java/com/backend/backend/message/Message.java
backend/src/main/java/com/backend/backend/message/MessageController.java
backend/src/main/java/com/backend/backend/message/MessageDto.java
backend/src/main/java/com/backend/backend/message/MessageMapper.java
backend/src/main/java/com/backend/backend/message/MessageRepository.java
backend/src/main/java/com/backend/backend/message/MessageService.java
backend/src/main/java/com/backend/backend/message/MessageServiceImpl.java
backend/src/main/java/com/backend/backend/user/User.java
backend/src/main/java/com/backend/backend/user/UserController.java
backend/src/main/java/com/backend/backend/user/UserService.java
backend/src/main/java/com/backend/backend/user/UserServiceImpl.java
fightme_webapp/lib/main.dart
fightme_webapp/pubspec.lock
fightme_webapp/pubspec.yaml

Backend has minimal functionality for messaging.

Merge request for backend. 

---

fightme_webapp/lib/Models/chatroom.dart
fightme_webapp/lib/Models/user.dart
fightme_webapp/lib/main.dart
fightme_webapp/pubspec.lock

Rebase integration on top of main

Integration fixed

---

fightme_webapp/lib/Models/httpservice.dart
fightme_webapp/lib/Models/message.dart
fightme_webapp/lib/chat_page.dart
fightme_webapp/lib/main.dart

Everything required for sprint 1

Sprint 1 Demo

---

backend/README.md

Added a section for sprint 2 goals. Should address at least 2 user stories through. the backend

Update README.md for Sprint 2 Goals

---

README.md

Added general things from the feedback we got from class

Updated README.md for Spring 2 goals

---

fightme_webapp/lib/home.dart
fightme_webapp/lib/main.dart
fightme_webapp/lib/navbar.dart

if you navigate to a widget that calls navbar a the bottom you will get a nested navbar.

Navigation

---

backend/README.md
backend/src/main/java/com/backend/backend/user/Dto/StatsDto.java
backend/src/main/java/com/backend/backend/user/User.java
backend/src/main/java/com/backend/backend/user/UserController.java
backend/src/main/java/com/backend/backend/user/UserMapper.java
backend/src/main/java/com/backend/backend/user/UserService.java
backend/src/main/java/com/backend/backend/user/UserServiceImpl.java

Added attackscore, defensescore, magicscore to user and being able to update all of them all in one api call. Be sure to update every user in db to have each of these.

Added 3 score attributes to user and Put request for them

---

backend/src/main/java/com/backend/backend/friendrequest/FriendRequest.java
backend/src/main/java/com/backend/backend/friendrequest/FriendRequestServiceImpl.java
fightme_webapp/lib/Models/friend_request.dart
fightme_webapp/lib/Models/httpservice.dart

made it so that if 2 users somehow sent a friend request to each other, if one or the other accepts or rejects, it makes both the requests accepted or rejected

Friend request frontend

---

backend/src/main/java/com/backend/backend/friendrequest/FriendRequestRepository.java
backend/src/main/java/com/backend/backend/friendrequest/FriendRequestServiceImpl.java

Implemented a feature where if a user sent a friend request and got rejected, that user cannot send another friend request. But if the rejectee wants to send a friend request to them back to them, they can.

2nd chance feature for friend request implemented

---

fightme_webapp/lib/chat_page.dart
fightme_webapp/lib/globals.dart
fightme_webapp/lib/home.dart
fightme_webapp/lib/main.dart
fightme_webapp/lib/navbar.dart

added imports to globals.dart in a few files and created globals.dart

globalval.dart addition

---

backend/README.md
backend/src/main/java/com/backend/backend/auth/AuthController.java
backend/src/main/java/com/backend/backend/auth/AuthRepository.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomDto.java
backend/src/main/java/com/backend/backend/friendrequest/FriendRequest.java
backend/src/main/java/com/backend/backend/message/Message.java
backend/src/main/java/com/backend/backend/message/MessageController.java
backend/src/main/java/com/backend/backend/message/MessageDto.java
backend/src/main/java/com/backend/backend/message/MessageServiceImpl.java
backend/src/main/java/com/backend/backend/user/User.java
backend/src/main/java/com/backend/backend/user/UserRepository.java

Implemented simple form style authentication for the backend. Did very simple testing for sign up and login, did not do any further testing so this maybe broken besides the auth part.
Check updated readme for how to authentication.

Very Very Simple Authentication for User Registration and Login

---

backend/README.md
backend/src/main/java/com/backend/backend/chatroom/ChatroomController.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomMapper.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomRepository.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomService.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomServiceImpl.java
backend/src/main/java/com/backend/backend/chatroom/Dto/ChatroomCreateDto.java
backend/src/main/java/com/backend/backend/chatroom/Dto/ChatroomDto.java

- Refactored how to create chatrooms so that you only need to send user IDs and itll create it and return the same JSON.
- Implemented getting the chatrooms of a certain user.
- Implemented deleting chatrooms
- Updated readme for how to use it.

Improving Chatrooms

---

backend/src/main/java/com/backend/backend/user/UserController.java
backend/src/main/java/com/backend/backend/user/UserService.java
backend/src/main/java/com/backend/backend/user/UserServiceImpl.java
fightme_webapp/lib/Models/httpservice.dart
fightme_webapp/lib/chats_master_page.dart
fightme_webapp/lib/navbar.dart
fightme_webapp/lib/searchbar.dart

Implemented a search for new friends to find in the chat master page so that users can find other friends to add. The search doesn't include you or your friends because you can check those already but for new users, this search will be very helpful. When searching, you can click and it'll take them to their page. Should be ready to merge!
Closes #2

Friend search functionality

---

fightme_webapp/lib/Models/httpservice.dart
fightme_webapp/lib/Widgets/fightButton.dart
fightme_webapp/lib/Widgets/friend_request_button.dart
fightme_webapp/lib/chat_page.dart
fightme_webapp/lib/gamerscore_shop.dart
fightme_webapp/lib/profile_page.dart
fightme_webapp/pubspec.yaml

- Implemented a way to look at your gamerscore in the profile page. You only should be able to see your own gamerscore. 
- Implemented a way to spend your gamerscore by going to the gamerscore shop in the profile page.
- Implemented a way to earn gamerscore by 
- Messaging (50% chance)
- Accepting Friend Request

GamerScore Feature

---

fightme_webapp/lib/Models/httpservice.dart
fightme_webapp/lib/globals.dart
fightme_webapp/lib/home.dart
fightme_webapp/lib/main.dart
fightme_webapp/lib/navbar.dart

Adds login page as default page and allows other pages to use global session to request data from backend

Login page and global login persistence

---

fightme_webapp/lib/Models/auth_clear.dart
fightme_webapp/lib/fight_game_page.dart
fightme_webapp/lib/home.dart
fightme_webapp/lib/main.dart
fightme_webapp/lib/navbar.dart
fightme_webapp/lib/profile_page.dart
fightme_webapp/macos/Flutter/GeneratedPluginRegistrant.swift
fightme_webapp/pubspec.lock
fightme_webapp/pubspec.yaml

- Created a separate page for login and signup. 
- Updated the UI for each for fresher design
- Made the login/signup persistent

Login and Signup Feature

---

README.md
backend/README.md

Reworked the backend README.md and updated main project README.md for sprint 3 goals

Readme rework

---

backend/README.md
backend/pom.xml
backend/src/main/java/com/backend/backend/auth/AuthController.java
backend/src/main/java/com/backend/backend/chatroom/ChatroomController.java
backend/src/main/java/com/backend/backend/friendrequest/FriendRequestController.java
backend/src/main/java/com/backend/backend/message/MessageController.java
backend/src/main/java/com/backend/backend/user/UserController.java
backend/src/main/java/com/backend/backend/websocket/MessageControllerWS.java
backend/src/main/java/com/backend/backend/websocket/WebSocketConfig.java
fightme_webapp/lib/Models/httpservice.dart
fightme_webapp/lib/chat_page_web_socket.dart
fightme_webapp/lib/chats_master_page.dart
fightme_webapp/lib/home.dart
fightme_webapp/pubspec.lock
fightme_webapp/pubspec.yaml

Implemented WebSockets more specifically STOMP messaging into the backend and flutter frontend.
Backend: 
- Implemented websocket/stomp config 
- Implemented websockt message controller
Frontend: 
- Implemented the exact same page as the chatpage but with websocket implementation.
Bugs: 
- I ran into some bugs with loading chatrooms when clicking on the nav bar. It would just do the circular progress indicator forever for some reason. The way i worked around this is by using another user that isn't bugged.

Web Socket Implementation for Messaging

---

.github/workflows/verifyBackendPR.yml
backend/README.md
backend/pom.xml
backend/src/test/java/com/backend/backend/IntegrationTest.java

Hopefully this doesn't break the main branch but this should include CI for our project. Plus there is java backend testing that is used in the github actions

GitHub actions + Backend (simple) Testing

---

fightme_webapp/lib/Cosmetics/profile_pictures.dart
fightme_webapp/lib/Models/httpservice.dart
fightme_webapp/lib/Providers/friends_provider.dart
fightme_webapp/lib/Providers/settings_provider.dart
fightme_webapp/lib/Providers/stats_provider.dart
fightme_webapp/lib/Widgets/fightButton.dart
fightme_webapp/lib/Widgets/friend_request_button.dart
fightme_webapp/lib/chat_page.dart
fightme_webapp/lib/chat_page_web_socket.dart
fightme_webapp/lib/chats_master_page.dart
fightme_webapp/lib/fight_game_page.dart
fightme_webapp/lib/gamerscore_shop.dart
fightme_webapp/lib/globals.dart
fightme_webapp/lib/home.dart
fightme_webapp/lib/leaderboard_page.dart
fightme_webapp/lib/main.dart
fightme_webapp/lib/profile_page.dart
fightme_webapp/lib/settings_page.dart

Added Settings Page + State Management (some) 

---

backend/src/main/java/com/backend/backend/gaming/Matchmaking.java
backend/src/main/java/com/backend/backend/gaming/SpriteGeneration.java
backend/src/main/java/com/backend/backend/gaming/StatSprite.java
backend/src/main/java/com/backend/backend/websocket/gaming/MatchmakingHandler.java
backend/src/main/java/com/backend/backend/websocket/gaming/gameWSConfig.java
backend/src/main/java/com/backend/backend/websocket/messaging/MessageControllerWS.java
backend/src/main/java/com/backend/backend/websocket/messaging/WebSocketConfig.java
fightme_webapp/lib/dungeon_lobby.dart
fightme_webapp/lib/fight_game_page.dart
fightme_webapp/lib/game/FightGame.dart
fightme_webapp/lib/training_area_page.dart

Dungeon multiplayer
